### ISSUE TITLE
Resize Formula

### ISSUE THREAD

**Issue by lucaslois** [jonathanhecl/IndeXAO#1]
https://github.com/jonathanhecl/IndeXAO/blob/23a20d99eaba593c311cabdc34b0a9ca342e6980/IndeXAO/Form1.cs#L271

Para el tema del Resize tenés que calcular el Aspect Ratio entre el Width y el Height. Si tu imagen original tiene un `image.width` e `image.height` determinados, el ratio será:

`ratio = image.width / image.height`, si vos luego modificas una de las dos variables para hacer el resize, tenés que ajustar la otra medida pasando por el ratio.

Si editás el Width:
```
image.width = anotherValue
image.height = image.width / ratio
```
o si editás el Height:
```
image.height= anotherValue
image.width= image.width * ratio
```

**Comment by jonathanhecl** [comment]
Dale, gracias, lo consideraré ;)
